apiVersion: v1
kind: Config
clusters:
- name: minikube
  cluster:
    certificate-authority-data: <вставь содержимое ca_base64.txt>
    server: https://127.0.0.1:51001
contexts:
- name: github-actions-context
  context:
    cluster: minikube
    user: github-actions-user
users:
- name: github-actions-user
  user:
    token: <вставь содержимое token.txt>
current-context: github-actions-context

